### ISSUE TITLE
'clickable: true/false' option

### ISSUE THREAD

**Issue by Derkades** [ServerSelectorX/ServerSelectorX#108]
Use case:
```
online:
  clickable: true
offline:
  clickable: true
dynamic:
  'whitelisted:true':
    clickable:false
```
Option defaults to true if not specified
