### ISSUE TITLE
Errors on /ssx reload and /ssx-custom:<menu>

### ISSUE THREAD

**Issue by Andre601** [ServerSelectorX/ServerSelectorX#144]
I receive the following NullPointerException when running /ssx reload
https://gist.github.com/Andre601/b528320ef96caa0a18d4634c328ffee0#file-ssx-reload

And also a CommandException when running /ssx-custom:\<menu> (Item did no longer work)
https://gist.github.com/Andre601/b528320ef96caa0a18d4634c328ffee0#file-ssx-custom

**Comment by Derkades** [comment]
This is most likely a configuration error, please attach your menu file

**Comment by Andre601** [comment]
Here is the content of the default.yml
I want to point out that I checked it with a yaml validator and that it didn't return any errors.

```yaml
# Please see this wiki article for an explanation for every option in this config
# https://github.com/ServerSelectorX/ServerSelectorX/wiki/Premium-menu-items-2.0.0

title: '&3EndStar > &8Server Selector'
rows: 5

item:
  enabled: true
  title: '&bServer Selector'
  lore:
  - ''
  - '&7Right click to open the Server selector.'
  material: NETHER_STAR
  on-join: 
    enabled: true
    inv-slot: 4
  right-click: true
  left-click: false

commands:
- menu
- servers
 
#permission:
#  open: true
#  message: '&cYou do not have permission to open this menu.'
#  item: false

url-message: '&3&lClick here'

menu:
  13:
    action: 'none'
    item: NETHER_STAR
    name: '&aLobby'
    lore:
    - ''
    - '&7The main Server from which'
    - '&7you can connect to all the'
    - '&7different gamemodes.'
    - ''
    - '&a&oYou are currently here.'
  19:
    action: 'srv:ma-1'
    online:
      item: ZOMBIE_HEAD
      name: '&bMobArena'
      lore:
      - ''
      - '&7Fight with others against swarms'
      - '&7of monsters and earn gold for'
      - '&7upgrades!'
      - ''
      - '&a&oClick to connect.'
    offline:
      item: RED_STAINED_GLASS_PANE
      name: '&cMobArena [Offline]'
      lore:
      - ''
      - '&7Fight with others against swarms'
      - '&7of monsters and earn gold for'
      - '&7upgrades!'
      - ''
      - '&cThis server is currently offline.'
  25:
    action: 'srv:bb-1'
    online:
      item: SCAFFOLDING
      name: '&aBuildBattle'
      lore:
      - ''
      - '&7Try to build the current theme of'
      - '&7the game as best as possible to win!'
      - ''
      - '&a&oClick to connect.'
    offline:
      item: RED_STAINED_GLASS_PANE
      name: '&cBuildBattle [Offline]'
      lore:
      - ''
      - '&7Try to build the current theme of'
      - '&7the game as best as possible to win!'
      - ''
      - '&cThis server is currently offline.'
  30:
    action: 'srv:survival'
    online:
      item: PODZOL
      name: '&6Ultra Survival'
      lore:
      - ''
      - '&7Just like normal survival but with'
      - '&7a twist!'
      - '&7Here you can die at any given time,'
      - '&7even while being offline. So be careful.'
      - ''
      - '&a&oClick to connect.'
    offline:
      item: RED_STAINED_GLASS_PANE
      name: '&cUltra Survival [Offline]'
      lore:
      - ''
      - '&7Just like normal survival but with'
      - '&7a twist!'
      - '&7Here you can die at any given time,'
      - '&7even while being offline. So be careful.'
      - ''
      - '&cThis server is currently offline.'
  32:
    action: 'none'
    online:
      item: PAPER
      name: '&cComing soon'
      lore:
      - ''
      - '&7We are working on a new game'
      - '&7for you to play.'
      - '&7Stay tuned!'
      - ''
      - '&a&oClick to connect.'
    offline:
      item: RED_STAINED_GLASS_PANE
      name: '&cComing soon'
      lore:
      - ''
      - '&7We are working on a new game'
      - '&7for you to play.'
      - '&7Stay tuned!'
      - ''
      - '&cThis server is currently offline.'
  -1: # -1 means all blank slots
    item: GRAY_STAINED_GLASS_PANE
    name: ' '
```
