### ISSUE TITLE
SSX Free does not show when server is offline when it is offline

### ISSUE THREAD

**Issue by Blocksnmore** [ServerSelectorX/ServerSelectorX#153]
I am using the legacy version (the big text) of ssx and I have an issue where the server will never be shown as offline when it is offline for me. here is a part of my config. I get no errors in console

```
menu:

  # Item in 4th slot (use 0 for first item). Add as many items as you want by copying this section and giving it a new number.
  3:

    # https://github.com/ServerSelectorX/ServerSelectorX/wiki/Free-%7C-Server-Pinging
    ping-server: true
    ip: not.a.real.ip
    port: 00006
    
    # https://github.com/ServerSelectorX/ServerSelectorX/wiki/Actions
    action: 'cmd:bungeeplayer move minigamehub'

    # Change item count based on number of players online. Only works if server pinging is set up. 
    # If there are more than 64 players online, the item count will be 1. Change how this works in config.yml.
    change-item-count: true
    
    # This value is ignored when change-item-count is turned on.
    item-count: 1

    # Online is used when ping-server is turned off, or ping-server is turned on and the server is online.
    online:
      item: WOOD
      data: 0
      name: '&aKitPvP Server'
      lore:
      # Placeholders not working? https://github.com/ServerSelectorX/ServerSelectorX/wiki/FAQ#placeholders-are-not-working
       - 'There are {online} out of {max} players online.'
       - 'Message of the day: {motd}'
      
    # Offline is used when ping-server is turned on and the server is offline.
    offline:
      item: WOOL
      data: 0
      name: '&cKitPvP Server'
      lore:
       - Ipsum lorem
       - Amet sit dolor
       - The server is offline
```

it always shows the online message no matter what. I am using the default config with only a few things changed to make sure it is as accurate as possible to the default config
