### ISSUE TITLE
Allow specifying multiple slots for one item

### ISSUE THREAD

**Issue by Derkades** [ServerSelectorX/ServerSelectorX#183]
```yaml
menu:
  '2,4,8,9,10':
    material: STONE
    ...
```
