### ISSUE TITLE
Show current server

### ISSUE THREAD

**Issue by Derkades** [ServerSelectorX/ServerSelectorX#66]
Would look something like this:
```
online:
   item: WOOL
    data: 0
offline:
   item: WOOL
    data: 15
current:
    item: WOOL
     data: 5
```
Use bungeecord plugin messaging channels for getting server name
